### ISSUE TITLE
Plugin incompatible?

### ISSUE THREAD

**Issue by war4peace** [ManuelMcLure/OctoPrint-WiFiStatus#1]
Hi, I was unable to find the plugin in the plugin repository, so I have installed it from the URL.
Now it shows up in the plugin list, but it looks like it's incompatible with OctoPrint.

![image](https://user-images.githubusercontent.com/6294884/95574196-414c5c80-0a35-11eb-8b67-4c8463bfa935.png)

**Comment by n3roGit** [comment]
Here the same! did it the same way like you

**Comment by Kkervinjones** [comment]
I've just found this out.  You need to update your Python to version 3.  Follow the instructions at https://octoprint.org/blog/2020/09/10/upgrade-to-py3/ to do this.

**Comment by n3roGit** [comment]
I  still have version 3

**Comment by Deses** [comment]
I have the same issue, and Python 3 is installed.

```
pi@octopi:~ $ python3 --version
Python 3.7.3
```

And other plugins using python 3 are working perfectly fine.

**Comment by penright** [comment]
I too am having an issue, but mine is the plugin is just grayed out. I started to open a different issue but while I was trying to gather up some info, I found this in the logs ...
```
2020-10-09 13:36:41,441 - octoprint.environment - INFO - Detected environment is Python 2.7.16 under Linux (linux2). Details:
|  hardware:
|      cores: 4
|      freq: 1200.0
|      ram: 916783104
|  os:
|      id: linux
|      platform: linux2
|  plugins:
|      pi_support:
|          model: Raspberry Pi 3 Model B Rev 1.2
|          octopi_version: 0.17.0
|  python:
|      pip: 19.3.1
|      version: 2.7.16
|      virtualenv: /home/pi/oprint

```
I thought just upgraded to the newest OctopPrint thinking I was getting the newest python.
![image](https://user-images.githubusercontent.com/21042538/95598265-5618f800-0a15-11eb-87ce-4f14e7970264.png)

But this link https://community.octoprint.org/t/does-octoprint-1-4-0-and-later-only-run-under-python-3-now-did-octoprint-stop-supporting-python-2/18322 says different.

**Comment by penright** [comment]
I just upgraded to python 3.
You have to be on OctoPi 17. I now see the difference between OctoPi and OctoPrint versions.
I used this URL and the wifi plugin now works for me. This was the only plugin I had that required python 3.
https://octoprint.org/blog/2020/09/10/upgrade-to-py3/

Basically, it runs these two commands.
```
  curl -L https://get.octoprint.org/py3/upgrade.py --output upgrade.py
  python3 upgrade.py
```
Here was my output just for reference ...
```
pi@octopi:~ $ mkdir python3upgrade
pi@octopi:~ $ cd python3upgrade/
pi@octopi:~/python3upgrade $ curl -L https://get.octoprint.org/py3/upgrade.py --output upgrade.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154  100   154    0     0    257      0 --:--:-- --:--:-- --:--:--   257
100 25622  100 25622    0     0  30321      0 --:--:-- --:--:-- --:--:-- 30321
pi@octopi:~/python3upgrade $ ls
upgrade.py
pi@octopi:~/python3upgrade $ python3 upgrade.py
OctoPrint Upgrade to Py 3 (v2.1.11)

Hello!
This script will move your existing OctoPrint configuration from Python 2 to Python 3
This script requires an internet connection and it will disrupt any ongoing print jobs.

It will install the latest version of OctoPrint (1.4.2) and all plugins.
No configuration or other files will be overwritten

Press [enter] to continue or ctrl-c to quit

Detecting system info...
OctoPi version: 0.17.0
Getting OctoPrint version...
OctoPrint version: 1.4.2
Reading installed plugins...

Plugins installed
- PrettyGCode
- Google Drive Backup
- Marlin GCode Documentation
- Backup Scheduler
- OctoPrint-WiFiStatus
- ABL Expert Plugin
If you think there is something missing from here, please check the list of plugins in Octoprint
Press [enter] to continue or ctrl-c to quit

Root access is required to install python3-dev, please fill in the password prompt if shown
Updating package list...
[sudo] password for pi:
Installing python3-dev...
Use 'sudo apt autoremove' to remove them.
Successfully installed python3-dev
Creating new Python 3 environment...
/usr/lib/python2.7/dist-packages/virtualenv.py:1090: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Successfully created Python 3 environment at /home/pi/oprint

Installing OctoPrint... (This may take a while - Do not cancel!)
Collecting required packages
Installing collected packages
OctoPrint successfully installed!

Downloading OctoPrint's plugin repo

Installing Auto bed leveling expert
Collecting required packages
Installing collected packages
Plugin Auto bed leveling expert successfully installed
Installing OctoPrint-PrettyGCode
Collecting required packages
Installing collected packages
Plugin OctoPrint-PrettyGCode successfully installed
Installing Backup Scheduler
Collecting required packages
Installing collected packages
Plugin Backup Scheduler successfully installed
Installing Google Drive Backup
Collecting required packages
Installing collected packages
Plugin Google Drive Backup successfully installed
Installing MarlinGcodeDocumentation
Collecting required packages
Installing collected packages
Plugin MarlinGcodeDocumentation successfully installed
Installing WiFi Status
Collecting required packages
Installing collected packages
Plugin WiFi Status successfully installed

Cleaning up...
Finished! OctoPrint should be ready to go
Once you have verified the install works, you can safely remove the folder /home/pi/oprint.bak
If you want to go back (If it doesn't work) to Python 2 download the file at:
https://raw.githubusercontent.com/cp2004/Octoprint-Upgrade-To-Py3/master/go_back.py
pi@octopi:~/python3upgrade $ sudo apt autoremove
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  libllvm8 rpi-eeprom-images
0 upgraded, 0 newly installed, 2 to remove and 1 not upgraded.
After this operation, 56.8 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 47814 files and directories currently installed.)
Removing libllvm8:armhf (1:8-3+rpi1) ...
Removing rpi-eeprom-images (9.0-1) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
pi@octopi:~/python3upgrade $

```

**Comment by cp2004** [comment]
@Deses  - you may have Python 3 on the system, but who knows if you have installed OctoPrint to it. Run this if you are using OctoPi: `~/oprint/bin/python --version`

As mentioned, you can upgrade by following the instructions in the blog post: [Upgrade your OctoPrint install to Python 3](https://octoprint.org/blog/2020/09/10/upgrade-to-py3/) - this cannot happen automatically, you must manually run the script.

@n3roGit - follow the instructions in the blog post, and you should be good. If not, then you have a different problem.

**Comment by Deses** [comment]
Ohhh I see, I was pretty convinced that Octoprint updated itself not too long ago! Now I remember that I didn't run that script because I still had some plugins using Python 2.

**Comment by penright** [comment]
The other bit of terminology I learn, there is a difference between supporting/using vs requires.
![image](https://user-images.githubusercontent.com/21042538/95615535-009d1500-0a2e-11eb-922e-cfbdc87dd6cd.png)
At the bottom of every plugin, there is the python it supports. Notice the wifi is >=3.7,<4. Whereas my Gcode documentation is >=2.7,<4.

**Comment by ManuelMcLure** [comment]
This is not a bug. The plugin listing specifies that it is only supported if OctoPrint is running under Python 3.7 or higher.
