### ISSUE TITLE
[BUG] [v.1.4.0] Informations are "hidden"

### ISSUE THREAD

**Issue by arut16** [ManuelMcLure/OctoPrint-WiFiStatus#12]
**Describe the bug**
Icon is there but then clicking on it to show informations, infobox in like hidden...

**To Reproduce**

1. Click on wifistatus icon

**Expected behavior**
Infobox shows by overlay informations on wifi

**Screenshots**
Before click : 
![image](https://user-images.githubusercontent.com/58274805/101987548-f51bd380-3c94-11eb-92a9-d5726a121913.png)
After click : 
![image](https://user-images.githubusercontent.com/58274805/101987567-1381cf00-3c95-11eb-98cd-17664ba16c5d.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser : Chrome 
- Version : 87.0.4280.88
- Octoprint 1.5.2 
- Python 3.7.3 
- OctoPi 0.17.0

**Comment by ManuelMcLure** [comment]
It looks like UI Customizer is breaking the dropdown. I'll take a look and see if I can figure out why.

**Comment by ManuelMcLure** [comment]
Turning off "Improve Mobile/Responsive" in the UI Customizer settings fixes this. I believe this to be a UI Customizer bug.

**Comment by arut16** [comment]
> Turning off "Improve Mobile/Responsive" in the UI Customizer settings fixes this. I believe this to be a UI Customizer bug.

Issue solved ! Thanks 👍😊!!
![IMG_20201212_195515](https://user-images.githubusercontent.com/58274805/101992514-38396f00-3cb4-11eb-80b3-af9b56a84ebf.jpg)

**Comment by LazeMSS** [comment]
It's fixed in the latest release of UI Customizer (https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.1.2)
Please test and confirm - thanks

**Comment by arut16** [comment]
> It's fixed in the latest release of UI Customizer (https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.1.2)
> Please test and confirm - thanks

Just installed latest release of UI Customizer. Issue solved with "Improve Mobile/responsive" !
Thanks !
