### ISSUE TITLE
WiFi status always showing not connected [BUG]

### ISSUE THREAD

**Issue by Blackdragon4034** [ManuelMcLure/OctoPrint-WiFiStatus#16]
after updating to 1.5.4 my WiFi status is always displaying the no connection symbol. It does seem to work when I change the settings from AUTO to wlan0

![Capture](https://user-images.githubusercontent.com/56185327/112272128-843e7b80-8cc7-11eb-8002-db9ab596657b.JPG)

**Comment by staffert** [comment]
Same issue here.
Just cleaned the plugin data and completely reinstalled it fresh as of last night, still no difference.

browser.user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0
connectivity.connection_check: 8.8.8.8:53
connectivity.connection_ok: true
connectivity.enabled: true
connectivity.online: true
connectivity.resolution_check: octoprint.org
connectivity.resolution_ok: true
env.hardware.cores: 4
env.hardware.freq: 1500
env.hardware.ram: 3959304192
env.os.bits: 32
env.os.id: linux
env.os.platform: linux
env.plugins.pi_support.model: Raspberry Pi 4 Model B Rev 1.2
env.plugins.pi_support.octopi_version: 0.18.0
env.plugins.pi_support.throttle_state: 0x0
env.python.pip: 20.3.3
env.python.version: 3.7.3
env.python.virtualenv: true
octoprint.safe_mode: false
octoprint.version: 1.5.3

**Comment by sbaghdadi** [comment]
+1 Same for me

**Comment by luco85** [comment]
And here!

**Comment by garyt72** [comment]
I'm seeing the same behavior as well.  I had to revert to v1.5.2 using the URL below to get it working normally again.

https://github.com/ManuelMcLure/OctoPrint-WiFiStatus/archive/refs/tags/1.5.2.zip

**Comment by ManuelMcLure** [comment]
Please try the new release 1.5.5 that I just created.

**Comment by arut16** [comment]
Had same issue. Fixed with 1.5.5 just installed.
![image](https://user-images.githubusercontent.com/58274805/112348678-54dc3e80-8cc8-11eb-8cb3-9f6ccb819040.png)

**Comment by ManuelMcLure** [comment]
Fixed in 1.5.5.
