### ISSUE TITLE
[BUG] Auto Wifi Status not working after last update (WiFi Status Plugin: 1.5.4)

### ISSUE THREAD

**Issue by tonnic** [ManuelMcLure/OctoPrint-WiFiStatus#17]
**Describe the bug**
Wifi symbol now has a slash through it and when moving mouse over it to show info, the text disappears behind main screen (I'm also using UI customizer).  When I go into the plugin settings and change from AUTO to wlan0 it works fine.

**To Reproduce**
2 of 3 octoprints have this issue -- last one is still on OctoPrint-WiFiStatus (1.5.2) and working fine on AUTO.

**Expected behavior**
Thought the plugin was broken as I never changed settings.  Found out that when I changed from AUTO to wlan0, everything works fine.

**Comment by ManuelMcLure** [comment]
Please try 1.5.5 and see if this problem still occurs.

**Comment by ManuelMcLure** [comment]
Ping @tonnic  - did 1.5.5 fix it for you?

**Comment by ManuelMcLure** [comment]
Closing as I have not received any feedback from submitter.
