### ISSUE TITLE
[BUG] Latest update, 1.7.0, does not display correctly with dark theme

### ISSUE THREAD

**Issue by Taomyn** [ManuelMcLure/OctoPrint-WiFiStatus#19]
**Describe the bug**
I upgraded from the previous release to 1.7.0, needed to uninstall/reinstall due to not updating bug with Octoprint 1.7.0RC3, but now it does not display correctly with my dark themed Octoprint and is unreadable.

**To Reproduce**

1. Upgraded as described above

**Expected behavior**
Should appear correctly coloured

**Screenshots**
As you can see all the others appear correct for the theme

![image](https://user-images.githubusercontent.com/4365929/135745521-6d3b3d93-6ab2-4113-ae10-5455a003f42f.png)

** Server**
Describe the server environment - what distribution and version of Linux on what hardware?
Is this an OctoPi installation or something different?
browser.user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36
connectivity.connection_check: 192.168.1.1:53
connectivity.connection_ok: true
connectivity.enabled: true
connectivity.online: true
connectivity.resolution_check: octoprint.org
connectivity.resolution_ok: true
env.hardware.cores: 4
env.hardware.freq: 1500
env.hardware.ram: 3971153920
env.os.bits: 32
env.os.id: linux
env.os.platform: linux
env.plugins.pi_support.model: Raspberry Pi 4 Model B Rev 1.2
env.plugins.pi_support.octopi_version: 0.18.0
env.plugins.pi_support.throttle_state: 0x0
env.python.pip: 21.2.4
env.python.version: 3.7.3
env.python.virtualenv: true
octoprint.safe_mode: false
octoprint.version: 1.7.0rc3
printer.firmware: Marlin v2.0.x (Sep 18 2021 09:56:18)
systeminfo.generator: systemapi

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Brave
- Version 1.30

**Logs**
I'll supply logs if you think they would be useful

**Additional context**
Themify Settings

![image](https://user-images.githubusercontent.com/4365929/135745580-001706f9-01be-4fc6-8864-aebe45e1968a.png)

**Comment by ManuelMcLure** [comment]
Unfortunately, this is a bug in Themify. Themeify doesn't properly style popovers: https://github.com/Birkbjo/OctoPrint-Themeify/issues/107 . I don't know when or if this will get fixed - there hasn't been a new release of Themeify in over a year.
Unfortunately working around this requires a bunch of hard-to-maintain javascript, so I'd rather avoid it if possible.
One workaround is to use [UI Customizer](https://plugins.octoprint.org/plugins/uicustomizer/) instead of Themeify - it also supports dark themes and they properly theme popovers.

**Comment by Taomyn** [comment]
@ManuelMcLure you were saying

![image](https://user-images.githubusercontent.com/4365929/135894054-d0def7ce-9aba-418d-bb90-404b1544794c.png)

**Comment by ManuelMcLure** [comment]
Looks like that theme doesn’t properly set popover colors either. The developer of UI Customizer is pretty responsive so I’ll ping him about it.

**Comment by Taomyn** [comment]
> Looks like that theme doesn’t properly set popover colors either. The developer of UI Customizer is pretty responsive so I’ll ping him about it.

I should have said thanks for pointing out the plug-in, it does seem to be far better than Themeify

**Comment by ManuelMcLure** [comment]
As a workaround for the popovers using the Dark Green theme in UI Customizer, add the following to the "Custom CSS" in the UI Customizer "Advanced" settings:
```
.popover {
  background-color: var(--darkish);
  border-color: var(--green);
}
.popover-title {
  background-color: var(--notquiteBlack);
  border-color: var(--green);
}
```

**Comment by Taomyn** [comment]
Perfect, seems to work

![image](https://user-images.githubusercontent.com/4365929/135893946-c96e9943-3671-4669-b93d-4fdcfa21f22c.png)

**Comment by ManuelMcLure** [comment]
I've provided a PR to the UICustomizer themes repository to fix this permanently: https://github.com/LazeMSS/OctoPrint-UICustomizerThemes/pull/33
For Themeify, it's possible that the following will improve things for the themes that don't support popovers properly (paste this into the Advanced settings):
```
.themeify.discorded .popover {
    background-color: rgb(54, 57, 63);
}

.themeify.discorded .popover .popover-title{
    background-color: rgb(47, 49, 54);
}
.themeify.discorded .popover.bottom .arrow:after{
    border-bottom-color: rgb(47, 49, 54);
}


.themeify.material_ui_light .popover{
    background-color: rgb(255, 255, 255);
}

.themeify.material_ui_light .popover .popover-title {
    background-color: rgba(0, 0, 0, 0);
}

.themeify.material_ui_light .popover.bottom .arrow:after{
    border-bottom-color: rgba(0, 0, 0, 0);
}


.themeify.cyborg .popover{
    background-color: rgb(6, 6, 6);
}

.themeify.cyborg .popover .popover-title {
    background-color: #fafafa;
}

.themeify.cyborg .popover.bottom .arrow:after{
    border-bottom-color: #fafafa;
}


.themeify.discoranged .popover{
    background-color: #36393f;
}

.themeify.discoranged .popover .popover-title {
    background-color: rgb(47, 49, 54);
}

.themeify.discoranged .popover.bottom .arrow:after{
    border-bottom-color: rgb(47, 49, 54);
}



.themeify.dyl .popover{
    background-color: #fff;
}

.themeify.dyl .popover .popover-title {
    background-color: rgb(255, 152, 0);
}

.themeify.dyl .popover.bottom .arrow:after{
    border-bottom-color:rgb(255, 152, 0);
}


.themeify.nighttime .popover{
    background-color: rgb(52, 56, 60);
}

.themeify.nighttime .popover .popover-title {
    background-color: rgb(64, 69, 74);
}

.themeify.nighttime .popover.bottom .arrow:after{
    border-bottom-color:rgb(64, 69, 74);
}
```
I don't use Themeify any more so I can't confirm that works.
