### ISSUE TITLE
No Options

### ISSUE THREAD

**Issue by n3roGit** [ManuelMcLure/OctoPrint-WiFiStatus#2]
After I have updated to Python3 the plugin starts too. So far so good.

Unfortunately I only see the symbol in the nav bar, even though I deleted the browser cache. No options or clicking possible.

![image](https://user-images.githubusercontent.com/8565847/95719796-a213a900-0c70-11eb-9f96-3197a5d22dd6.png)

**Comment by Raphael713** [comment]
if you hover the mouse on top of it, it'll show the stats...

However a option to turn on/off features would be great, for example, show the IP

**Comment by n3roGit** [comment]
Ah okay thx!

**Comment by ManuelMcLure** [comment]
@Raphael713 If you have specific features that you are interested in please open a feature request. I want to avoid feature creep as much as possible, but if a feature makes sense I'll take a look.

@n3roGit if @Raphael713's comment answered your question please close the issue.
