### ISSUE TITLE
[Feature Request] Plugin isn't theme-able currently

### ISSUE THREAD

**Issue by borkedporcupine** [ManuelMcLure/OctoPrint-WiFiStatus#20]
Currently the plugin ignores current theme.  Would be nice if the plugin was theme-able like other system assets.  On darker themes it's a bit difficult to read currently.  

![Theme_wifi](https://user-images.githubusercontent.com/79605150/137022346-a06468d5-203f-49cf-9e06-78a3ae68435b.JPG)

**Comment by ManuelMcLure** [comment]
Let me guess - Themeify? Themeify does not properly theme popovers - this is a Themeify bug: https://github.com/Birkbjo/OctoPrint-Themeify/issues/107

I would suggest switching to UI Customizer instead of Themeify - it has more functionality, and properly themes popovers. The Discoranged  theme you are using is also available in UI Customizer.

**Comment by borkedporcupine** [comment]
> Let me guess - Themeify? Themeify does not properly theme popovers - this is a Themeify bug: [Birkbjo/OctoPrint-Themeify#107](https://github.com/Birkbjo/OctoPrint-Themeify/issues/107)
> 
> I would suggest switching to UI Customizer instead of Themeify - it has more functionality, and properly themes popovers. The Discoranged theme you are using is also available in UI Customizer.

Ah ok, good info, I did not know that.  I will check out UI Customizer instead.  Thanks for the help and quick reply.

**Comment by ManuelMcLure** [comment]
You're welcome. The developer of UI Customizer is very responsive - a fix was just added for the only UI Customizer theme that did _not_ properly theme popovers (Dark Green) so it should now look correct regardless of the theme you pick.

**Comment by borkedporcupine** [comment]
> You're welcome. The developer of UI Customizer is very responsive - a fix was just added for the only UI Customizer theme that did _not_ properly theme popovers (Dark Green) so it should now look correct regardless of the theme you pick.

Yea just switched over, already like this a LOT better than what I had before.  This replaces about three plugins.

**Comment by ManuelMcLure** [comment]
Closing.
