### ISSUE TITLE
[FR] Physical button to turn on/off WiFi

### ISSUE THREAD

**Issue by M4rkoV2** [ManuelMcLure/OctoPrint-WiFiStatus#21]
For some reason when I start printing my internet connection starts lagging.

Can you add feature that if GIPOx is HIGH then WiFi is ON, but if GIPOx is LOW than WiFI is OFF?

That way I could easy disconnect PI after setting up printing.

**Comment by ManuelMcLure** [comment]
Adding any sort of control functionality to the plugin is outside the feature scope I want to stay within. Sorry.
