### ISSUE TITLE
[Feature Request] Add netmask and gateway (and DNS) options

### ISSUE THREAD

**Issue by b-morgan** [ManuelMcLure/OctoPrint-WiFiStatus#22]
In addition to the option to show the IPV4 (or IPV6) address, please add an option(s) to display the netmask and the gateway address. The DNS server(s) would also be useful.

This additional information could be useful when troubleshooting network issues like failure to connect via SSH.

**Comment by ManuelMcLure** [comment]
Hi, I'm planning to add netmask and gateway information, since those are easy to obtain using the libraries already in use. DNS information is much trickier since there's no clean API to retrieve it and I'd need to parse `resolv.conf` so I'm not planning to add that feature, sorry.

**Comment by ManuelMcLure** [comment]
Release 1.8.0 should show up soon  with netmask and gateway options.
