### ISSUE TITLE
[Feature Request] Add show all interfaces feature.

### ISSUE THREAD

**Issue by aaronkogan** [ManuelMcLure/OctoPrint-WiFiStatus#23]
Now, if I have more than one Wi-Fi adapter, I need to go into settings and select one of them to display. It's not very helpful. It will be great to add a feature to show all interfaces in the settings to display it in the octoprint status bar.

**Comment by ManuelMcLure** [comment]
Because having more than one WiFi adapter is a very uncommon case and it would be impossible for me to test since I don't have a system configured in that way, I am not planning to add this feature, sorry.
