### ISSUE TITLE
[BUG] After install of 1.7.2 it claims that there is an update to 1.7.2

### ISSUE THREAD

**Issue by b-morgan** [ManuelMcLure/OctoPrint-WiFiStatus#24]
**Describe the bug**
After install of 1.7.2 it claims that there is an update to 1.7.2

**To Reproduce**

1. Click "Update Now" in the Update Available dialog
2. Click on "Reload Now"
3. Click "Update Now" in the Update Available dialog
4. Click on "Reload Now"

**Expected behavior**
I expect only one Update Available (i.e. I don't expect an infinite loop).

** Server**
OctoPi 0.18.0, OctoPrint 1.9.0rc5, RPi 3B (with RPi camera 2.1)
What version of Python is OctoPrint running under? 3.7.3

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 112.0.5615.138 (Official Build) (64-bit)

**Logs**
[octoprint-logs.zip](https://github.com/ManuelMcLure/OctoPrint-WiFiStatus/files/11402003/octoprint-logs.zip)

**Comment by ManuelMcLure** [comment]
Is this the first time you have installed the plugin? This is the first report of this issue with 1.7.2 and it was released over a year ago. There was an earlier release that had an upgrade issue, can you confirm if you upgraded from another release?

**Comment by b-morgan** [comment]
Yes, I had a previous release installed (so that release may have been 1.7.2) as I usually keep my plugins up to date.

Should I uninstall and reinstall?

**Comment by ManuelMcLure** [comment]
There was an old release which had a problem that would cause an upgrade cycle, but that was back in the 1.6.x days if I recall correctly. But uninstalling and reinstalling _should_ solve the problem.

**Comment by b-morgan** [comment]
Uninstall and reinstall did indeed fix the problem.
