### ISSUE TITLE
No status symbol, plugin de-activated when octoprint is restarted

### ISSUE THREAD

**Issue by sohxet** [ManuelMcLure/OctoPrint-WiFiStatus#4]
Hi.
The plugin doesn't work - the symbol doesn't appear and when the server is restarted the plugin becomes disabled.
Octoprint version: 1.4.2
Octopi version: 0.17
Kernel: 4.19.75-v7+ #1270
Raspberry pi 2B+

**Comment by sohxet** [comment]
The raspi 2B+ doesn't have onboard wifi, I use an external adapter and needed to configure wpa_supplicant manually. Could that be related?

**Comment by ManuelMcLure** [comment]
Have you upgraded your OctoPrint installation to run under Python 3? The plugin only works if OctoPrint is running on Python 3.7 or higher. Please check out https://github.com/cp2004/Octoprint-Upgrade-To-Py3 for a script that will allow you to upgrade your OctoPrint installation to run under Python 3.

**Comment by ManuelMcLure** [comment]
If the above comment answered your question, please close the issue.

**Comment by sohxet** [comment]
Yes this worked, thanks.
