### ISSUE TITLE
[ENHANCEMENT] Please add connected AccessPoint name in tooltip

### ISSUE THREAD

**Issue by rknobbe** [ManuelMcLure/OctoPrint-WiFiStatus#5]
**Describe the bug**
I tried to add WirelessInfo(interface).getAPaddr() to a new "bssid" field in net_data, and display it in static/js/wifistatus.js, but getAPaddr() always comes back as "undefined". I guess I'm not following how to use iwconfig vs iwlist in pythonwifi. Note that in my network, the AP name doesn't show up with iwlist, it only shows up using iwconfig, as  in

```
pi@octopi:~/oprint/lib/python3.7/site-packages/octoprint_wifistatus $ iwconfig wlan0
wlan0     IEEE 802.11  ESSID:"myaccesspoint"
          Mode:Managed  Frequency:5.26 GHz  Access Point: 9C:3D:CF:1E:AE:84
          Bit Rate=200 Mb/s   Tx-Power=31 dBm
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          Link Quality=59/70  Signal level=-51 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:11  Invalid misc:0   Missed beacon:0

```
I have more than one AP in my environment, and would like to see which AP is connected from the Octoprint GUI.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 81.0.1

**Additional context**

Running Octoprint on a Raspberry Pi 4, Raspbian 10 (buster) with Python 3.7.3 and the current github release of OctoPrint-WifiStatus (1.0.0)

**Comment by rknobbe** [comment]
![Capture](https://user-images.githubusercontent.com/802457/95792510-2ac33100-0cd3-11eb-9725-c6cc4ab3719e.PNG)

**Comment by rknobbe** [comment]
Disregard, I found and fixed my problem


```
__init__.py
            if not interface is None:
                net_data["bitrate"] = wifi.getBitrate()
                stat, qual, discard, missed_beacon = wifi.getStatistics()
                net_data["qual"] = qual.quality
                net_data["qual_max"] = wifi.getQualityMax().quality
                net_data["signal"] = qual.signallevel
                net_data["noise"] = qual.noiselevel
                #net_data["bssid"] = WirelessInfo(interface).getAPaddr();
                net_data["bssid"] = wifi.getAPaddr()
```


```
static/js/wifistatus.js
                title = 'Interface: ' + data.interface + '\n' +
                    'ESSID: ' + data.essid + '\n' +
                    'AP: ' + data.bssid + '\n' +
                    'Quality: ' + data.qual + '/' + data.qual_max + ' (' +
                quality + '%)\n' +
            'Bitrate: ' + data.bitrate + '\n' +
                    'Signal: ' + data.signal + 'dBm\n';
                if (data.noise != 0)
                    title += 'Noise: ' + data.noise + 'dBm\n';

```

**Comment by ManuelMcLure** [comment]
Honestly, this seems like a good idea. I'll get this added to the code. Thanks for the tip!

**Comment by ManuelMcLure** [comment]
The latest version disables this by default. There is now an Settings page where it can be enabled.
