### ISSUE TITLE
Show IP Address

### ISSUE THREAD

**Issue by cereyanli** [ManuelMcLure/OctoPrint-WiFiStatus#6]
It would be nice if assigned IP address displayed on mouse over

**Comment by ManuelMcLure** [comment]
Unfortunately, the library I use doesn't provide the IP address. Also, it's common that an interface will have more than one IP address (in my case my interface has an IPV4 address and six IPV6 addresses) which would greatly increase the size of the tooltip.

So at this time my inclination is to not add this functionality. Given that if you can connect to the web interface to see the WiFi icon you already have a hostname or IP that can be used to connect to the printer, I also fail to see if that would add much functionality.

**Comment by ManuelMcLure** [comment]
I have posted a new version with this functionality. By default the IP addresses will _not_ be shown - you need to enable them in the Settings page.

**Comment by cereyanli** [comment]
It works great. Thanks for considering it
