### ISSUE TITLE
[BUG] Button not clickable on Mobile Safari / Mobile Chrome

### ISSUE THREAD

**Issue by mcstoufer** [ManuelMcLure/OctoPrint-WiFiStatus#7]
**Describe the bug**
Button shows up correctly on mobile browsers, but tapping them does not display popover/tooltip

**To Reproduce**
1. Go to octopi site with this plugin installed.
2. Click on the wifi button.

**Expected behavior**
Some sort of display of content that is not triggered by a delayed hover action.

**Screenshots**
N/A

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
- Device: Any iPad/iPhone
 - OS: iOS 14.x
 - Browser: Both Chrome and Safari
 - Version both current releases

**Additional context**

**Comment by ManuelMcLure** [comment]
Please test out the new 1.3.1 release. Now the extra information is displayed by clicking or tapping the button instead of by hovering.

**Comment by ManuelMcLure** [comment]
Functionality is available in 1.3.1.
